---
# tasks file for instance.ethminer
- name: Docker pull image.
  shell: docker pull {{ ethminer_docker_image }}

- name: Create the {{ volume_path }}/bitcoin directory.
  file:
    path: "{{ volume_path }}/ethminer"
    state: directory

- name: Template ethminer systemd file.
  template:
    src: ethminer.service.j2
    dest: /etc/systemd/system/ethminer.service

- name: systemctl daemon-reload.
  command: systemctl daemon-reload
  changed_when: false

# - name: Start the ethminer service.
#   service:
#     name: ethminer
#     state: started
#     enabled: yes

