---
# tasks file for instance.nvidia_docker
# https://github.com/NVIDIA/nvidia-docker
- name: Install Docker apt key.
  shell: curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -

- name: Create the apt sources file.
  copy:
    src: nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list

- name: Update apt cache.
  apt:
    update_cache: yes
  changed_when: false

- name: Install Docker.
  apt:
    name: "nvidia-docker2"
    state: present
  register: apt_nvidia_docker

- name: Reload Systemd.
  command: systemctl daemon-reload
  changed_when: false

- name: Restart Docker.
  service:
    name: nvidia-docker2
    state: restarted
  when: apt_nvidia_docker.changed

- name: Ensure Docker is started.
  service:
    name: nvidia-docker2
    state: started
