# ethminer.yml
# Initial raw configuration
- hosts: localhost
  become: yes
  gather_facts: no
  user: ubuntu
  roles:
    - role: ubuntu.raw_install_python

- hosts: localhost
  become: yes
  gather_facts: yes
  user: ubuntu
  roles:
    - role: instance.ssh_aws_public_key
    - role: instance.packages
    - role: instance.docker_apt_repo
    - role: instance.nvidia_docker
    - role: instance.prometheus_node_exporter
    - role: instance.ethminer
      tags:
        - eth
